{
    "name": "LocalButtonPress",
    "version": "1.0.76",
    "icon": "fab fa-battle-net",
    "category": "automation",
    "author": "mjlill",
    "maintainers": [
        "Psycho",
        "maxbachmann"
    ],
    "desc": "Press an imaginary button on or off",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [
        "RPi.GPIO"
    ],
    "conditions": {
        "lang": [
            "en"
        ]
    }
}